resolver: lts-12.13

allow-newer: true

packages:
  - '.'

extra-deps:
  - megaparsec-7.0.0
  - llvm-hs-pure-7.0.0
  - llvm-hs-7.0.1
  - github: mattaudesse/llvm-hs-pretty
    commit: 811af2c

flags:
  llvm-hs:
    shared-llvm: true
